### ISSUE TITLE
Any insights about performance?

### ISSUE THREAD

**Issue by rocboronat** [aryarohit07/PicassoFaceDetectionTransformation#1]
Hi @aryarohit07 ! First: thanks for your work :·)

One question: do you have numbers about the impact in performance? It could be great to add it in the readme.

Thanks!

**Comment by aryarohit07** [comment]
Hi @rocboronat , yes I do have numbers and I will put the same in the next release. :)

**Comment by rocboronat** [comment]
Great! Feel free to close the issue if you want to maintain the issues list clean :-)

**Comment by aryarohit07** [comment]
Will close it after next release.

**Comment by aryarohit07** [comment]
Updated [README](https://github.com/aryarohit07/PicassoFaceDetectionTransformation/blob/master/README.md) with performance stats. :)
