### ISSUE TITLE
Please add sample

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [aryarohit07/PicassoFaceDetectionTransformation#2]
To show that it works nicely.
Maybe make a RecyclerView that has 3 images per row:  original, center-crop, and using your library.
And, the images will be from the device itself (like the gallery app).

**Comment by aryarohit07** [comment]
I have already added samples in the readme. It contains all three image versions i.e., original, center-crop and face-center-crop.

**Comment by AndroidDeveloperLB** [comment]
I meant a real sample, that we can run on the device.
Not screenshots.
