### ISSUE TITLE
android.content.res.Resources$NotFoundException: Resource ID #0xc8

### ISSUE THREAD

**Issue by aishwarya080416** [aryarohit07/PicassoFaceDetectionTransformation#3]
Hey,
I am getting the error mentioned in the question.

`Picasso.with(this) 
                .load(url)
                .fit()
                .centerInside()
                .transform(new FaceCenterCrop(200, 200, FaceCenterCrop.DP))
                .into(ivOne);`

I don't get the error if I comment the .transform(...) line.

**Comment by aryarohit07** [comment]
If you are trying to use `DP` instead of Pixel then you will have to enter **resource id**. Something like this:
`new FaceCenterCrop(R.dimen.some_value, R.dimen.some_other_value, FaceCenterCrop.DP)`

**Comment by aishwarya080416** [comment]
Thank you! Working perfectly! :)
